"use client";

import { useState } from "react";
import { Footer } from "@/components/footer";
import { motion } from "framer-motion";
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from "recharts";
import TextHoverAnimation from "@/components/textHoverAnimation";
import TabSEO from "@/components/seoOptimize";
import { seoData } from "@/common/seoTitleDescription";
import jsPDF from "jspdf";

const COLORS = ["#00C49F", "#FF8042"];
const grassTypes = [
  {
    name: "Rubber Infilled",
    type: "rubber",
    indoorRange: [260, 280],
    outdoorRange: [460, 480],
  },
  {
    name: "Eco Friendly",
    type: "eco",
    indoorRange: [280, 320],
    outdoorRange: [490, 520],
  },
  {
    name: "Aqua Eco Friendly",
    type: "aqua",
    indoorRange: [330, 360],
    outdoorRange: [530, 570],
  },
];

export default function TurfCalculator() {
  const [formData, setFormData] = useState({
    environment: "indoor",
    grassType: "rubber",
    size: 3000,
    name: "",
    email: "",
    phone: "",
    timeline: "",
  });
  const [result, setResult] = useState<number | null>(null);

  const calculateEstimate = () => {
    const grass = grassTypes.find((g) => g.type === formData.grassType);
    const [min, max] =
      formData.environment === "indoor"
        ? grass!.indoorRange
        : grass!.outdoorRange;
    const avgRate = (min + max) / 2;
    const cost = avgRate * formData.size;
    setResult(cost);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    const logoBase64 = "/game_on_logo.webp"; // Replace with your real logo string

    // Add Logo
    doc.addImage(logoBase64, "PNG", 15, 10, 30, 30);

    // Heading beside logo
    doc.setFont("helvetica", "bold");
    doc.setFontSize(20);
    doc.text("GameOn Solution", 105, 20, { align: "center" });

    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(40);
    doc.text("Turf Cost Estimate Report", 105, 30, { align: "center" });

    // Divider
    doc.setDrawColor(200);
    doc.line(20, 40, 190, 40);

    let y = 50;

    // Personal Info
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text(`Name:`, 20, y);
    doc.text(formData.name || "-", 70, y);
    y += 10;
    doc.text(`Email:`, 20, y);
    doc.text(formData.email || "-", 70, y);
    y += 10;
    doc.text(`Phone:`, 20, y);
    doc.text(formData.phone || "-", 70, y);
    y += 10;
    doc.text(`Timeline:`, 20, y);
    doc.text(formData.timeline || "-", 70, y);
    y += 15;

    // Project Info
    doc.setFont("helvetica", "bold");
    doc.text("Project Details", 20, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.text(`Environment:`, 20, y);
    doc.text(formData.environment, 70, y);
    y += 10;
    doc.text(`Grass Type:`, 20, y);
    const grass = grassTypes.find((g) => g.type === formData.grassType);
    doc.text(grass?.name || "-", 70, y);
    y += 10;
    doc.text(`Ground Size:`, 20, y);
    doc.text(`${formData.size} sq.ft`, 70, y);
    y += 15;

    // Cost
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 128, 0);
    doc.setFontSize(14);
    doc.text("Estimated Cost", 20, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(13);
    doc.setTextColor(0);
    doc.text(`Turf Cost: ₹${result?.toLocaleString()}`, 20, y);
    y += 10;
    doc.setTextColor(0, 102, 204);
    doc.setFont("helvetica", "bold");
    doc.text(`Total Estimate: ₹${result?.toLocaleString()}`, 20, y);

    // Footer
    y += 30;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by GameOn Solution | www.gameonsolution.in", 105, y, {
      align: "center",
    });

    doc.save("Turf-Cost-Estimate.pdf");
  };

  const pieData = result
    ? [
        { name: "Turf Cost", value: result },
        { name: "Others", value: 0 },
      ]
    : [
        { name: "Turf Cost", value: 0 },
        { name: "Others", value: 0 },
      ];

  return (
    <>
      <TabSEO
        title="Turf Cost Calculator | GameOn Solution"
        description="Calculate accurate turf installation costs based on size, grass type, and environment. Trusted by South India's top sports infra developers."
        keywords="Turf Cost Calculator, GameOn Solution, sports infrastructure, artificial turf cost, turf installation India"
        image={seoData.blog.image}
        url="https://gameonsolution.in/turf-calculator"
      />

      <main className="min-h-screen bg-gradient-to-br from-green-950 to-black text-white px-6 md:px-20 pt-28 pb-16">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="text-center max-w-4xl mx-auto mb-12"
        >
          <p className="uppercase text-secondary text-sm tracking-widest font-secondary">
            Instant Estimate
          </p>
          <h1 className="text-4xl md:text-5xl font-primary uppercase">
            <TextHoverAnimation text="Turf Calculator" />
          </h1>
          <p className="mt-4 text-lg text-gray-300">
            GameOn Solution presents India’s most advanced{" "}
            <strong>AI-assisted Turf Calculator</strong>. Instantly estimate
            costs for your sports turf based on area, environment, and
            eco-friendly material choices.
          </p>
        </motion.div>

        <section className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, x: -30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="bg-white/10 rounded-2xl shadow-2xl p-8 backdrop-blur-md"
          >
            <div className="grid gap-5">
              <input
                type="text"
                placeholder="Your Name"
                className="w-full p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.name}
                onChange={(e) =>
                  setFormData({ ...formData, name: e.target.value })
                }
              />
              <input
                type="email"
                placeholder="Email Address"
                className="w-full p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.email}
                onChange={(e) =>
                  setFormData({ ...formData, email: e.target.value })
                }
              />
              <input
                type="tel"
                placeholder="Mobile Number"
                className="w-full p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.phone}
                onChange={(e) =>
                  setFormData({ ...formData, phone: e.target.value })
                }
              />
              <select
                className="w-full p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.timeline}
                onChange={(e) =>
                  setFormData({ ...formData, timeline: e.target.value })
                }
              >
                <option value="">Select Construction Time</option>
                <option value="15 Days">15 Days</option>
                <option value="1 Month">1 Month</option>
                <option value="45 Days">45 Days</option>
                <option value="2 Months">2 Months</option>
              </select>

              <select
                className="w-full mt-1 p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.environment}
                onChange={(e) =>
                  setFormData({ ...formData, environment: e.target.value })
                }
              >
                <option value="indoor">Indoor</option>
                <option value="outdoor">Outdoor</option>
              </select>

              <select
                className="w-full mt-1 p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.grassType}
                onChange={(e) =>
                  setFormData({ ...formData, grassType: e.target.value })
                }
              >
                {grassTypes.map((g) => (
                  <option key={g.type} value={g.type}>
                    {g.name}
                  </option>
                ))}
              </select>

              <input
                type="number"
                className="w-full mt-1 p-3 rounded-xl bg-black/60 text-white border border-gray-700"
                value={formData.size}
                onChange={(e) =>
                  setFormData({ ...formData, size: +e.target.value })
                }
                placeholder="Ground Size (sq.ft)"
              />

              <button
                onClick={calculateEstimate}
                className="w-full mt-4 bg-secondary text-black font-semibold py-3 rounded-xl hover:bg-yellow-400 transition"
              >
                Calculate Estimate
              </button>
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, x: 30 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.6 }}
            className="flex flex-col items-center"
          >
            <h2 className="text-2xl font-bold mb-6 text-secondary uppercase">
              Estimated Cost Breakdown
            </h2>
            <ResponsiveContainer width="100%" height={250}>
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={60}
                  outerRadius={90}
                  dataKey="value"
                  label
                >
                  {pieData.map((_, index) => (
                    <Cell
                      key={`cell-${index}`}
                      fill={COLORS[index % COLORS.length]}
                    />
                  ))}
                </Pie>
                <Tooltip />
              </PieChart>
            </ResponsiveContainer>
            {result && (
              <div className="mt-6 text-center">
                <p className="text-xl text-white mb-2">
                  <span className="font-semibold text-secondary">Total:</span> ₹
                  {result.toLocaleString()}
                </p>
                <button
                  onClick={exportPDF}
                  className="mt-3 px-6 py-2 rounded-md bg-white/10 border border-yellow-400 text-yellow-300 hover:bg-yellow-400 hover:text-black transition"
                >
                  Download PDF
                </button>
              </div>
            )}
          </motion.div>
        </section>
      </main>

      <Footer />
    </>
  );
}
